#!/bin/sh
#
# Default Memory Map for OMAP3530 EVM
#
# Start Addr    Size    Description
# -------------------------------------------
# 0x80000000     99 MB  Linux
# 0x86300000     15 MB  CMEM
# 0x87200000     14 MB  CODEC SERVER


load () {
    modprobe cmemk phys_start=0x86300000 phys_end=0x87200000 allowOverlap=1
    modprobe dsplinkk
    modprobe lpm_omap3530
    modprobe sdmak
    mknod /dev/dsplink c `awk "\\$2==\"dsplink\" {print \\$1}" /proc/devices` 0
}

unload () {
    rmmod cmemk
    rmmod lpm_omap3530
    rmmod dsplinkk
    rmmod sdmak
}

case "$1" in
      start) 
            load
             ;;
       stop) 
            unload           
             ;;
       restart) 
            unload           
            load
             ;;
        *)
             echo "$0 <start/stop/restart>"
             ;;
esac

