#!/bin/sh


case "$1" in
    start )
        if [ -e /dev/mmcblk0p1 -a -e /dev/mmcblk0p3 ]
        then
            modprobe g_mass_storage file=/dev/mmcblk0p1,/dev/mmcblk0p3
        fi
    ;;
    stop )
        lsmod | grep g_mass_storage > /dev/null
        if [ "$?" == "0" ]
        then
            rmmod g_mass_storage
        fi
    ;;
esac

exit 0
