SRCREV = "295"
PR_append = "-arago1"

SRC_URI += "file://0001-ti814x-Add-Description-Pages-for-DSP-Menu.patch;striplevel=2 \
            file://0002-ti81xx-Remove-touchscreen-calibration.patch;striplevel=2 \
            file://0003-ti814x-Set-Video-Demos-to-1080p30.patch;striplevel=2 \
            file://0004-ti814x-Add-Video-Demos.patch;striplevel=2 \
            file://0005-ti816x-Update-runOMTB-not-to-pause.patch;striplevel=2 \
            file://0006-ti814x-Fix-the-text-for-getting-started.patch;striplevel=2 \
            file://0007-ti814x-Correct-CMEM-in-DSP-Benchmarks.patch;striplevel=2 \
            file://0008-ti814x-Fix-Calibration.patch;striplevel=2 \
"
