#!/bin/sh



#
# In order to view video, the graphics plane needs to be
# disabled. Once the video has finished playing the graphics
# plane needs to be re-enabled. 
#
# Call this function with 0 to disable graphics and 1 to
# enable it.
# 
configure_graphics()
{
    echo $1 > /sys/devices/platform/vpss/graphics0/enabled
}

# 
# Call this function to setup and execute the demo 
# 
execute_demo()
{
   gst-launch v4l2src num-buffers=300  always-copy=false queue-size=5 ! 'video/x-raw-yuv-strided,format=(fourcc)YUY2,width=720,height=480,framerate=(fraction)30/1' ! omxbufferalloc numBuffers=5 ! gstperf ! v4l2sink min-queued-bufs=2 
}


# Disable Graphics Plane so that Video can be seen.
configure_graphics 0

execute_demo
    
# Enable Graphics again.
configure_graphics 1
