#!/bin/sh

if [ -e /usr/share/ti/ti-omtb ] 
then
    # Disable Graphics Plane so that Video can be seen.
    echo 0 > /sys/devices/platform/vpss/graphics0/enabled
    echo 0 > /sys/devices/platform/vpss/graphics1/enabled
    
    cd /usr/share/ti/ti-omtb
    
    if [ -e /tmp/OMTB.lock ]
    then 
       ./unpause_omx.xv5T test_pipe U

       sleep 60
    else
       touch /tmp/OMTB.lock
       ./omtb_dm816xbm_a8host.xv5T dual_display_encode_decode.oms &
    
       sleep 60
    fi
    
    # Enable Graphics again.
    echo 1 > /sys/devices/platform/vpss/graphics1/enabled
    echo 1 > /sys/devices/platform/vpss/graphics0/enabled
fi
