#!/bin/sh



#
# In order to view video, the graphics plane needs to be
# disabled. Once the video has finished playing the graphics
# plane needs to be re-enabled. 
#
# Call this function with 0 to disable graphics and 1 to
# enable it.
# 
configure_graphics()
{
    echo $1 > /sys/devices/platform/vpss/graphics0/enabled
}

# 
# Call this function to setup and execute the demo 
# 
execute_demo()
{
    /usr/share/ti/videoloopbackdemo/vlb ntsc hdmi
}


# Disable Graphics Plane so that Video can be seen.
configure_graphics 0

execute_demo
    
# Enable Graphics again.
configure_graphics 1
