#!/bin/sh -e

exec > /dev/console 2>&1

export TZ=/etc/localtime

[ -f /etc/default/udev ] && . /etc/default/udev

echo "Caching udev devnodes"

set -- uname cmdline devices atags

if [ "$DEVCACHE" != "" ]; then
	find /dev ! -type d | grep -v -e ^/dev/.udev -e ^/dev/log |
		tar -T /proc/self/fd/0 -cf $DEVCACHE
	md5sum -b $DEVCACHE > $DEVCACHE.md5
	for x; do
		mv /tmp/$x /etc/udev/saved.$x || true
	done
	echo
else
	for x; do
		rm -f /tmp/$x
	done
fi

exit 0
